export const kpiData = [
  { title: 'Global Threats Neutralized (24h)', value: '1.2M', trend: '+7%', icon: 'ShieldCheck' },
  { title: 'Corporate Assets Protected', value: '4.7M', trend: '+15%', icon: 'Server' },
  { title: 'CVEs Exploited & Patched', value: '8,921', trend: '+3%', icon: 'Bug' },
  { title: 'Data Breach Incidents Prevented', value: '1,533', trend: '-2%', icon: 'DatabaseZap' },
];

export interface Tool {
  id: string;
  name: string;
  description: string;
  type: 'Free' | 'Premium';
  category: 'Red Team' | 'Blue Team' | 'Vulnerability Assessment';
  code?: string;
}

export const freeTools: Tool[] = [
    {
        id: 'free-01',
        name: 'ReconRaptor',
        description: 'Automated OSINT gathering and reconnaissance.',
        type: 'Free',
        category: 'Red Team',
        code: `const os = require('os');\nconsole.log('Scanning network:', os.networkInterfaces());`,
    },
    {
        id: 'free-02',
        name: 'PhishGuard',
        description: 'Analyze email headers for phishing indicators.',
        type: 'Free',
        category: 'Blue Team',
        code: `function analyzeHeader(header) {\n  return header.includes('spf=fail');\n}`,
    },
    {
        id: 'free-03',
        name: 'NetStalker',
        description: 'Fast network discovery and port scanning tool.',
        type: 'Free',
        category: 'Vulnerability Assessment',
        code: `import nmap\nnm = nmap.PortScanner()\nnm.scan('127.0.0.1', '22-443')`,
    },
    {
        id: 'free-04',
        name: 'CryptoCheck',
        description: 'Check for weak TLS/SSL configurations.',
        type: 'Free',
        category: 'Vulnerability Assessment',
        code: `import ssl\nimport socket\nhostname = 'example.com'\ncontext = ssl.create_default_context()\nsocket.create_connection((hostname, 443))`,
    },
    {
        id: 'free-05',
        name: 'PassHound',
        description: 'Identify weak and commonly used passwords.',
        type: 'Free',
        category: 'Red Team',
        code: `const commonPasswords = ['123456', 'password'];\nfunction checkStrength(pwd) {\n  return !commonPasswords.includes(pwd);\n}`,
    },
    {
        id: 'free-06',
        name: 'LogLense',
        description: 'A lightweight log file anomaly detector.',
        type: 'Free',
        category: 'Blue Team',
        code: `def find_anomalies(log_file):\n    for line in log_file:\n        if "ERROR" in line:\n            print(line)`,
    },
    {
        id: 'free-07',
        name: 'PayloadGen',
        description: 'Generate common XSS and SQLi payloads.',
        type: 'Free',
        category: 'Red Team',
        code: `const xssPayloads = ['<script>alert(1)</script>'];`,
    },
    {
        id: 'free-08',
        name: 'ConfigGaurd',
        description: 'Audit server configuration files for security.',
        type: 'Free',
        category: 'Blue Team',
        code: `cat /etc/ssh/sshd_config | grep "PermitRootLogin"`,
    },
    {
        id: 'free-09',
        name: 'DepShield',
        description: 'Scan project dependencies for known CVEs.',
        type: 'Free',
        category: 'Vulnerability Assessment',
        code: `npm audit`,
    },
    {
        id: 'free-10',
        name: 'HoneyPotter',
        description: 'Deploy a simple honeypot to trap attackers.',
        type: 'Free',
        category: 'Blue Team',
        code: `import socket\ns = socket.socket()\ns.bind(('0.0.0.0', 22))\ns.listen(5)`,
    },
    {
        id: 'free-11',
        name: 'DirBrute',
        description: 'Brute-force web server directories and files.',
        type: 'Free',
        category: 'Red Team',
        code: `import requests\nrequests.get('https://example.com/admin')`,
    },
    {
        id: 'free-12',
        name: 'HashCracker',
        description: 'Simple hash identification and cracking utility.',
        type: 'Free',
        category: 'Red Team',
        code: `import hashlib\nhashlib.md5(b'password').hexdigest()`,
    },
    {
        id: 'free-13',
        name: 'MalwareScan',
        description: 'Basic Yara rule scanner for local files.',
        type: 'Free',
        category: 'Blue Team',
        code: `import yara\nrules = yara.compile(filepath='my_rules')\nrules.match(filepath='some_file')`,
    },
    {
        id: 'free-14',
        name: 'ApiSentry',
        description: 'Monitor API endpoints for unusual traffic patterns.',
        type: 'Free',
        category: 'Blue Team',
        code: `function monitor(request) {\n  if(request.rate > 100) return 'blocked';\n}`,
    },
    {
        id: 'free-15',
        name: 'SubDomainiac',
        description: 'Enumerate subdomains of a target domain.',
        type: 'Free',
        category: 'Red Team',
        code: `import dns.resolver\ndns.resolver.resolve('google.com', 'A')`,
    },
    {
        id: 'free-16',
        name: 'JwtInspector',
        description: 'Decode and inspect JSON Web Tokens.',
        type: 'Free',
        category: 'Vulnerability Assessment',
        code: `import jwt\njwt.decode('ey...', options={"verify_signature": False})`,
    },
    {
        id: 'free-17',
        name: 'FirewallTest',
        description: 'Test firewall rules for common misconfigurations.',
        type: 'Free',
        category: 'Blue Team',
        code: `iptables -L`,
    },
    {
        id: 'free-18',
        name: 'CloudWatchr',
        description: 'Scan S3 buckets for public accessibility.',
        type: 'Free',
        category: 'Vulnerability Assessment',
        code: `import boto3\ns3 = boto3.client('s3')\nresponse = s3.list_buckets()`,
    },
    {
        id: 'free-19',
        name: 'ThreatWire',
        description: 'A simple RSS feed aggregator for threat intel.',
        type: 'Free',
        category: 'Blue Team',
        code: `import feedparser\nfeedparser.parse('https://threatpost.com/feed/')`,
    },
    {
        id: 'free-20',
        name: 'GitSleuth',
        description: 'Scan git repositories for leaked secrets.',
        type: 'Free',
        category: 'Vulnerability Assessment',
        code: `git log -p | grep "secret"`,
    },
];

export const premiumTools: Tool[] = [
    {
        id: 'prem-01',
        name: 'Aegis Automata',
        description: 'Automated Enterprise SIEM with AI-driven correlation.',
        type: 'Premium',
        category: 'Blue Team',
    },
    {
        id: 'prem-02',
        name: 'VulcanForge',
        description: 'Advanced Penetration Testing Suite with automated exploitation.',
        type: 'Premium',
        category: 'Red Team',
    },
    {
        id: 'prem-03',
        name: 'ThreatMatrix AI',
        description: 'Predictive threat modeling and attack surface management.',
        type: 'Premium',
        category: 'Vulnerability Assessment',
    },
    {
        id: 'prem-04',
        name: 'Helios IR',
        description: 'Incident response orchestration and digital forensics platform.',
        type: 'Premium',
        category: 'Blue Team',
    },
    {
        id: 'prem-05',
        name: 'Sentinel CSPM',
        description: 'Continuous cloud security posture and compliance management.',
        type: 'Premium',
        category: 'Blue Team',
    },
    {
        id: 'prem-06',
        name: 'RedTeamOS',
        description: 'A complete, containerized OS for red team operations.',
        type: 'Premium',
        category: 'Red Team',
    },
    {
        id: 'prem-07',
        name: 'AppDefend RASP',
        description: 'Runtime Application Self-Protection to block attacks in real-time.',
        type: 'Premium',
        category: 'Vulnerability Assessment',
    },
    {
        id: 'prem-08',
        name: 'Phalanx Deception',
        description: 'Enterprise-grade deception technology and honeynet management.',
        type: 'Premium',
        category: 'Blue Team',
    },
    {
        id: 'prem-09',
        name: 'AdversarySim',
        description: 'Breach and Attack Simulation (BAS) platform.',
        type: 'Premium',
        category: 'Red Team',
    },
    {
        id: 'prem-10',
        name: 'ComplianceFlow',
        description: 'Automated compliance mapping and evidence gathering.',
        type: 'Premium',
        category: 'Vulnerability Assessment',
    },
];

export const allTools = [...freeTools, ...premiumTools];
